const assert = require('node:assert/strict');
global.pressureEngine = require('../js/pressure.js');
const v = require('../js/validation.js');
const defaults=v.defaults();
assert.equal(defaults.goal,'','purpose must start blank');
for(const removed of ['socks','orthosis','supportSite','chair','handSupport','placementNote','note'])assert.equal(removed in defaults,false,`${removed} must not be a registration slot`);
const samples = Array.from({length:30},(_,i)=>({t:i*100,v:[100+i%3,200,300,400]}));
const good=v.baselineQuality(samples,0,3000);
assert.equal(good.ok,true);
assert.deepEqual(good.baseline,[101,200,300,400]);
assert.equal(v.baselineQuality(samples.slice(0,1),0,3000).ok,false,'one stale packet must not pass');
assert.equal(v.baselineQuality(samples.filter(s=>s.t<1000||s.t>2200),0,3000).ok,false,'receive gaps must not pass');
assert.equal(v.baselineQuality(samples.map(s=>({...s,v:[s.t,200,300,400]})),0,3000).ok,false,'moving baseline must not pass');
assert.equal(v.baselineQuality(samples.map(s=>({...s,v:[1023,200,300,400]})),0,3000).ok,false,'a channel fixed at saturation must not pass');
const nearMax=v.baselineQuality(samples.map((s,i)=>({...s,v:[1020+i%4,200,300,400]})),0,3000);
assert.equal(nearMax.ok,true,'near-saturation variation in shoes must remain measurable');
assert.ok(nearMax.warnings.length,'near-saturation variation must be surfaced as a warning');
const segment=[[0,100,0,20,0,1,2,3],[100,0,100,0,20,4,5,6],[200,10,30,40,50,7,8,9]];
assert.ok(segment.includes(v.referenceFromSegment(segment)),'representative must be a real observed sample');
const q=v.signalQuality([[0,1023,0,0,0],[100,0,0,0,0],[900,0,0,0,0]],1000);
assert.equal(q.maxGapMs,800);assert.equal(q.saturationPct,8.3);
assert.equal(v.signalQuality([],3000).count,0);
const original={conditionId:'a',task:'sit'};const frozen=v.copy(original);original.task='walk';assert.equal(frozen.task,'sit');
// Reset is deliberately limited to record keys and export/import preserves metadata.
const vm=require('node:vm'), fs=require('node:fs');
const data=new Map();const context={MAX_SENSOR_VAL:1023,DEFAULT_CAPTURE_CHANNELS:[],BUILD_VERSION:'test',localStorage:{getItem:k=>data.get(k)||null,setItem:(k,x)=>data.set(k,x),removeItem:k=>data.delete(k)}};
vm.createContext(context);vm.runInContext(fs.readFileSync(require.resolve('../js/store.js'),'utf8')+'\nglobalThis.storeTest=store;',context);
const store=context.storeTest;
store.saveSettings({audioVolume:.7});
store.saveCapture({captureId:'test-cap',context:frozen,markers:[{t:1,label:'보조 변경',note:'균형 지지'}],left:segment});
store.saveDrill({id:'d1',channels:[],points:[],context:frozen,source:{captureId:'test-cap'},referenceReviewRequired:true});
const backup=store.exportAll();store.resetExperimentRecords();
assert.equal(store.getCaptures().length,0);assert.equal(store.getDrills().length,0);assert.equal(store.getSettings().audioVolume,.7);
store.importAll(backup);assert.equal(store.getCapture('test-cap').markers[0].note,'균형 지지');
assert.equal(store.getDrill('d1').source.captureId,'test-cap');
console.log('validation tests: ok');
